*********ZCL_EUI_SCREEN-AUTO_GEN*********
*CAN_UPDATE=FALSE
REPORT DYNAMIC_SUBSCR.
TABLES:
USR02
.

SELECTION-SCREEN BEGIN OF SCREEN 9459 AS SUBSCREEN.
SELECTION-SCREEN BEGIN OF BLOCK bl_main WITH FRAME TITLE s_title.
PARAMETERS P_01 TYPE TCURY-BUKRS.
PARAMETERS P_02 TYPE ETTCD-MODE AS LISTBOX VISIBLE LENGTH 50.
PARAMETERS P_03 AS CHECKBOX.
SELECT-OPTIONS P_04 FOR USR02-BNAME. " <--- Change SH
PARAMETERS P_05 TYPE T005T-LAND1.
PARAMETERS P_06 TYPE SYST-INDEX.
PARAMETERS P_07 TYPE SYST-TABIX.

SELECTION-SCREEN END OF BLOCK bl_main.
SELECTION-SCREEN END OF SCREEN 9459.

AT SELECTION-SCREEN OUTPUT.
PERFORM AUTO_SCREEN_PBO IN PROGRAM SAPLZFG_EUI_SCREEN.
