*********ZCL_EUI_SCREEN-AUTO_GEN*********
*CAN_UPDATE=FALSE
REPORT dynamic_subscr.
TABLES:
  usr02.

SELECTION-SCREEN BEGIN OF SCREEN 9459 AS SUBSCREEN.
SELECTION-SCREEN BEGIN OF BLOCK bl_main WITH FRAME TITLE s_title.
PARAMETERS p_01 TYPE tcury-bukrs.
PARAMETERS p_02 TYPE ettcd-mode AS LISTBOX VISIBLE LENGTH 50.
PARAMETERS p_03 AS CHECKBOX.
SELECT-OPTIONS p_04 FOR usr02-bname. " <--- Change SH
PARAMETERS p_05 TYPE t005t-land1.
PARAMETERS p_06 TYPE syst-index.
PARAMETERS p_07 TYPE syst-tabix.

SELECTION-SCREEN END OF BLOCK bl_main.
SELECTION-SCREEN END OF SCREEN 9459.

AT SELECTION-SCREEN OUTPUT.
  CALL FUNCTION 'ZFM_EUI_PBO'.
